export {ClasseResourceService} from './services/classe-resource.service';
export {ComponenteResourceService} from './services/componente-resource.service';
export {DatasetResourceService} from './services/dataset-resource.service';
export {EntitaResourceService} from './services/entita-resource.service';
export {FascicoloResourceService} from './services/fascicolo-resource.service';
export {FunzionalitaResourceService} from './services/funzionalita-resource.service';
export {ProvinciaResourceService} from './services/provincia-resource.service';
export {AclResourceService} from './services/acl-resource.service';
export {IdpResourceService} from './services/idp-resource.service';
export {DownloadResourceService} from './services/download-resource.service'
